### ISSUE TITLE
Do we want to play with unit tests? See comments.

### ISSUE THREAD

**Issue by togfoxy** [togfoxy/MarsLander#162]
Do we want with a unit testing library or a 'code sanitiser' that looks for unused variable etc?

It might not be an efficient use of our time.
It might be a distraction.
It might not be easy to integrate.
It's not something we have to do.

Is it something we WANT to do - because we want to learn. Or try.  Or improve our discipline. Or because we like distractions. 

Establishing and executing would be entirely optional. Some will dabble. Some won't. 

I think there are good techniques/libraries and bad. I think we can remain open to 'light touch' libraries that have no or minimal impact on the code.

**Comment by MadByteDE** [comment]
I think that decision should be made by the two of you.

Personally I've never used anything like that in my code, so it might be possible that here and there something slipped through. But I'd say in all the years I code on and off over time, I developed a pretty good sense for optimizing my code so that there are no leaked local variables or duplicates.

I don't see any real issue with implementing something like that, so if you guys think it would help for your workflow, I wouldn't mind.

**Comment by MadByteDE** [comment]
I've just seen the love forum post & wasn't aware of the scope of what that means. 

Honestly, going hard on writing tests/asserts to verify something coming out of a function for such a small scope game project as Mars Lander doesn't seem like something we'd NEED. I don't say we don't need to test and verify our code at all, but spending a significant amount of time with writing tests instead of adding new features and iterating over the existing functionality feel like a waste of time to me.

If you want to do this to learn and improve, I mean sure. It's not something I'm interested in in particular - I'm more about getting better with game dev in general like game logic and techniques, asset creation, how to make a game fun. But if you think that's something you are interested in and want to learn more about it, sure. Give it a shot. :grin:

**Comment by Philbywhizz** [comment]
I've looked at using [busted](http://olivinelabs.com/busted/) for some of my other projects in the past and while I understand the concept of unit testing and TDD (Test Driven Development) I would struggle to keep the workflow cycle going.

The thing with unit tests is that everyone needs to be involved, otherwise the game code gets altered by one person who don't run the tests, and the tests suddenly don't work and becomes out of sync and needs effort to either update the tests or fix the game code (or both). An alternative is that you don't merge code in that don't pass the tests. This essentially becomes a 'blocker' for people wanting to submit code who don't use/like unit tests.

So as much as I would _like_ to do unit tests as a learning exercise, I don't think it would be useful for us here at the moment.

I do like the idea of a 'code sanitiser' or checker. I think you can hook it in these kind of checkers using github actions that automatically run when you push up a commit (I think it can do it for PR as well) and it checks the code for errors. I think this is something that could be useful.

**Comment by togfoxy** [comment]
Anything we do needs to be unobtrusive and optional. There are unit test modules that run outside the base code and you can choose to run them or not.

If we sometimes write tests and sometimes run the tests (ie not consistently) then any report/result will have reduced value but not zero value. I shall ponder.

**Comment by togfoxy** [comment]
I've used this in the past with some success and some frustration. It runs outside the code making it entirely optional for individuals to use.

https://love2d.org/forums/viewtopic.php?f=5&t=90074

We can even adjust it over time to align to our agreed style.

**Comment by togfoxy** [comment]
Closing this one as it is not interesting at this point.
